'use strict';

/**
 * Seed page-content collections (Experience, CommunityEvent, GenericPage).
 *
 * Runs on every Strapi boot, but is fully idempotent:
 *  - Only creates an entry if no entry exists for that slug
 *  - Never overwrites Anna's edits
 *
 * Goal: when Anna opens Strapi for the first time after this deploy, every
 * sub-page already has its current frontend copy pre-filled. She doesn't
 * have to retype anything — just upload images.
 */

async function ensure(strapi, uid, slug, data) {
  try {
    const existing = await strapi.documents(uid).findMany({
      filters: { slug },
      limit: 1,
    });
    if (existing && existing.length > 0) {
      // Entry exists — backfill any fields that are null/empty (new schema fields).
      // Never overwrites a field Anna has already filled.
      const current = existing[0];
      const patch = {};
      for (const [key, val] of Object.entries(data)) {
        const cur = current[key];
        if (cur === null || cur === undefined || cur === '') {
          patch[key] = val;
        }
      }
      if (Object.keys(patch).length > 0) {
        await strapi.documents(uid).update({
          documentId: current.documentId,
          data: patch,
          status: 'published',
        });
        strapi.log.info(`[seed-pages] Backfilled ${uid} (${slug}): ${Object.keys(patch).join(', ')}`);
      }
      return false;
    }
    await strapi.documents(uid).create({
      data: { ...data, slug },
      status: 'published',
    });
    strapi.log.info(`[seed-pages] Created ${uid} (${slug})`);
    return true;
  } catch (err) {
    strapi.log.warn(`[seed-pages] Skipped ${uid} (${slug}): ${err.message}`);
    return false;
  }
}

// Same as ensure() but for singleTypes (no slug — exactly one record per UID).
async function ensureSingleType(strapi, uid, data) {
  try {
    const existing = await strapi.documents(uid).findFirst({});
    if (existing) {
      // Backfill empty fields only
      const patch = {};
      for (const [key, val] of Object.entries(data)) {
        const cur = existing[key];
        if (cur === null || cur === undefined || cur === '') {
          patch[key] = val;
        }
      }
      if (Object.keys(patch).length > 0) {
        await strapi.documents(uid).update({
          documentId: existing.documentId,
          data: patch,
          status: 'published',
        });
        strapi.log.info(`[seed-pages] Backfilled singleType ${uid}: ${Object.keys(patch).join(', ')}`);
      }
      return false;
    }
    await strapi.documents(uid).create({
      data,
      status: 'published',
    });
    strapi.log.info(`[seed-pages] Created singleType ${uid}`);
    return true;
  } catch (err) {
    strapi.log.warn(`[seed-pages] Skipped singleType ${uid}: ${err.message}`);
    return false;
  }
}

async function seedPages(strapi) {
  // ═══ Membership singleType (Reset Room subscription) ═══
  await ensureSingleType(strapi, 'api::membership.membership', {
    title: 'The Reset Room',
    description: 'A monthly membership for women rebuilding their nervous system. Live calls, somatic library, a quiet room of women doing the work.',
    pricePence: 2500,
    currency: 'gbp',
    isRecurring: true,
    recurringInterval: 'month',
    mailchimpTag: 'Reset Room Members',
    grantsResetRoomAccess: true,
  });

  // ═══ Homepage singleType — every field backfilled with the frontend
  //     fallback values so Anna sees the actual content in CMS and can
  //     edit anything. Without this she opens Homepage and sees blank
  //     fields while the live site shows hardcoded copy.
  //     Auto-extracted via Docs/_extract_homepage_seed.py. Regenerate if
  //     frontend fallback copy changes. ═══
  // 87 fields extracted from web/app/page.tsx (auto-generated by Docs/_extract_homepage_seed.py)
  await ensureSingleType(strapi, 'api::homepage.homepage', {
    issueLine: "Issue No. 01 · Summer 2026",
    insideThisIssueLine: "Inside this issue",
    heroKicker: "Reset Stories",
    heroTitle: "Come back to yourself.",
    heroBody: "What does it actually feel like to live in full alignment with who you are? Not the managed version. Not the performing one. The whole one. We are exploring that here, through honest stories, real practices, and a life beautifully lived.",
    heroCtaPrimaryUrl: "/reset-stories",
    heroCtaPrimaryLabel: "Read the Reset Stories",
    heroCtaSecondaryUrl: "/the-work",
    heroCtaSecondaryLabel: "Work with Anna",
    featuredFallbackTitle: "You are not overwhelmed. You are holding everything.",
    featuredFallbackAuthor: "Anna Lou",
    featuredFallbackReadingTime: "6 min read",
    featuredFallbackExcerpt: "T",
    mantra1: "You don’t have to hold all of this. Come back to yourself.",
    quote1Text: "Maybe the next level isn’t about managing everything more gracefully. Maybe it’s about not gripping so tightly in the first place.",
    quote1Attribution: "Anna Lou",
    workKicker: "Work with Anna",
    workTitle: "Your inner world already knows.",
    workBody1: "Most people arrive here after trying everything else. The therapy. The journalling. The courses. The spiritual work. Getting all the way to the insight, and then hitting the same wall. This work meets you in the body, where the patterns actually live.",
    workBody2: "The Signal Method™ is the umbrella for all the coaching work here. Underneath it sit the programmes, each designed for a different stage of the journey.",
    workCtaPrimaryUrl: "/the-work",
    workCtaPrimaryLabel: "Start with the free Nervous System Decoder",
    workCtaSecondaryUrl: "/the-work/ways-to-work-with-me",
    workCtaSecondaryLabel: "Explore all the ways to work",
    exploreKicker: "Explore",
    exploreTitle: "Life, Love, and Work",
    exploreLifeBody: "Rituals and energy, home and space, style and beauty, food and nourishment, weekend finds.",
    exploreLoveBody: "Dating and patterns, breakups and reset, friendship, motherhood, self worth and identity.",
    exploreWorkBody: "Founder reset, burnout and nervous system, Signal Method™, career and direction, money and worth.",
    quote2Text: "Your inner guidance system was never broken. It was waiting for you to stop overriding it.",
    quote2Attribution: "Anna Lou",
    experiencesKicker: "Experiences",
    experiencesTitle: "Workshops, retreats, and reset days.",
    experiencesBody: "Group sessions held on the houseboat at Taggs Island, online, and in corporate spaces. A few times a year, a small group comes to the island for a full reset day. Water outside, no agenda, just space to come back to yourself.",
    experiencesCtaLabel: "Browse all experiences",
    newsletterKicker: "Reset Letters",
    newsletterTitle: "A letter, every week, that feels like coming home.",
    newsletterBody: "Honest, beautiful writing about your inner world, jewellery with meaning, houseboat life, and what it actually feels like to return to yourself.",
    newsletterFreeTierLabel: "Free",
    newsletterFreeTierBody: "One letter a month. The last Friday digest with a personal note from Anna.",
    newsletterPlusTierLabel: "Plus",
    newsletterPlusTierBody: "Everything weekly. Full Sunday Cosmic Forecast, Wednesday Signal Check, Friday ESJ Drop, monthly Reset Story, full archive, early event access.",
    newsletterCtaUrl: "/reset-letters",
    newsletterCtaLabel: "Join Reset Letters →",
    newsletterMicrocopy: "No spam. Honest writing. Cancel any time.",
    shopKicker: "Anna Lou of London",
    shopTitle: "Jewellery with meaning. Made to be worn.",
    shopBody: "I have been designing jewellery for over twenty-five years. What I have learned, across all of that, is that the pieces that actually matter are not the most expensive ones. They are the ones you reach for in hard moments. The ones that remind you.",
    shopProduct1Hook: "I reach for this one when I need to remember what is underneath the noise",
    shopProduct1Name: "Moonstone Necklace",
    shopProduct2Hook: "For the days my mind is doing too much and I need clarity not calm",
    shopProduct2Name: "Clear Quartz Necklace",
    shopProduct3Hook: "The word you keep coming back to, worn close to your throat",
    shopProduct3Name: "Personalised Phrase Necklace",
    shopCtaLabel: "Browse all jewellery",
    mediaKicker: "Watch · Listen · Read",
    mediaTitle: "The Reset with Anna.",
    mediaTile1Url: "#",
    mediaTile1Label: "YouTube",
    mediaTile1Title: "Come Back to Yourself — daily mantras and practices.",
    mediaTile1Meta: "Video series",
    mediaTile2Url: "#",
    mediaTile2Label: "Podcast",
    mediaTile2Title: "The Reset with Anna Lou — honest conversations about the inner world.",
    mediaTile2Meta: "Coming soon",
    mediaTile3Url: "/reset-letters",
    mediaTile3Label: "Substack",
    mediaTile3Title: "Reset Letters — weekly writing that feels like coming home.",
    mediaTile3Meta: "Weekly newsletter",
    quote3Text: "The feeling itself moves through in ninety seconds if you let it. Nine years of running from ninety seconds of feeling is an extraordinary amount of cardio.",
    quote3Attribution: "Anna Lou",
    communityKicker: "Community",
    communityTitle: "Come and sit with us.",
    communityBody1: "Every Tuesday I hold a circle at The Hare and the Moon, Twickenham. Donation-based. No agenda except being in the room together. Connection is not a concept. It is biological.",
    communityBody2: "The Returning Circle runs every week without exception. No waitlist needed. Come on Tuesday.",
    communityBody3: "A few times a year, a small group comes to Taggs Island, Hampton for a full reset day. Water outside, no agenda, just space to come back to yourself.",
    communityCta1Url: "/community/the-returning-circle",
    communityCta1Label: "The Returning Circle",
    communityCta2Url: "/community/reset-room",
    communityCta2Label: "The Reset Room",
    communityCta3Url: "/experiences/retreats",
    communityCta3Label: "Retreat days",
    portraitKicker: "About",
    portraitTitle: "Twenty-five years leaves a trail.",
    portraitBody: "F",
    portraitCtaUrl: "/about",
    portraitCtaLabel: "Read Anna’s story",
  });

  // ═══ Reset Room Page singleType — backfilled with frontend fallback copy
  //     (auto-extracted via Docs/_extract_homepage_seed.py). 32 fields.
  await ensureSingleType(strapi, 'api::reset-room-page.reset-room-page', {
    heroEyebrow: "Monthly somatic membership",
    heroTitle: "The Reset Room.",
    heroTagline: "Where the work moves from podcast to practice.",
    heroCtaLabel: "Join the Reset Room · £25/month",
    heroSecondaryLabel: "See what's inside",
    heroPriceStrip: "£25/month · No minimum term · Cancel any time",
    introLead: "The Reset Letters are the front door. The Reset Room is the room behind it.",
    introBody: "This is where the work stops being something you read and starts being something you practice. A members-only video room, a monthly live call with me, and a growing vault of guided journeys. All for £25 a month.",
    pillarsKicker: "What's inside",
    pillarsTitle: "Three pillars. One quiet room.",
    pillar1Kicker: "Reset Room Sessions",
    pillar1Name: "Bi-weekly intimate sessions",
    pillar1Body: "Two new intimate video sessions a month, the conversations that do not belong on the public feed. Watch in your own time, inside the room.",
    pillar1Bullets: "2 new sessions / month\nWatch any time inside the room\nFounding sessions already inside",
    pillar2Kicker: "The Reset Call",
    pillar2Name: "Monthly live with Anna",
    pillar2Body: "Ninety minutes with me, live on Zoom, first Thursday of every month. Bring your questions, sit with the group, leave with what you came for. Replay added to the room the next day.",
    pillar2Bullets: "1st Thursday, 7.30pm UK\n90 minutes, group format\nReplay live by Friday lunchtime",
    pillar3Kicker: "The Reset Vault",
    pillar3Name: "Signature journeys library",
    pillar3Body: "A growing library of guided somatic journeys. Music, breath, visualisation, embodiment. New piece every month. Where insight becomes the actual life.",
    pillar3Bullets: "7 founding journeys at launch\nNew journey added monthly\nVideo + audio, watch eyes-closed",
    alsoIncludedKicker: "Also included",
    alsoIncludedTitle: "The room comes with the rest of the house.",
    alsoIncluded1: "Workshop replays — every workshop I have ever run, free for you inside.",
    alsoIncluded2: "Forty-eight-hour members-only window on every new retreat before it goes public.",
    alsoIncluded3: "Ten percent off all 1:1 Reset Sessions and One Day intensives.",
    alsoIncluded4: "Members-only events that never go on the public calendar.",
    whoBody: "The Reset Room is for the woman who has been reading the Reset Letters, doing the work on her own, and is ready for something that holds her more closely.",
    priceTitle: "Step inside the room.",
    priceBody: "£25 a month. No minimum term. Cancel any time. Everything is delivered through the member portal you can come back to whenever you want.",
    priceCtaLabel: "Join the Reset Room",
  });

  // ═══ Reset Letters Page singleType — backfilled. 22 fields.
  await ensureSingleType(strapi, 'api::reset-letters-page.reset-letters-page', {
    whatItIsBody: "",
    eachWeekBody: "",
    voicesBody: "",
    aboutAnnaBody: "",
    founderBenefits: "",
    comingSoonLabel: "COMING SOON",
    strapline: "for women who have been holding everything",
    heroHeadline: "If you've been holding everything for a long time, this is for you.",
    heroBody1: "Reset Letters is a weekly magazine about what happens when you finally put it all down.",
    heroBody2: "It is written by me, Anna Lou, with contributions from coaches, therapists, and women I trust.",
    whatItIsTitle: "WHAT IT IS",
    eachWeekTitle: "EACH WEEK",
    voicesTitle: "VOICES & CONTRIBUTORS",
    aboutAnnaTitle: "A BIT ABOUT ANNA",
    launchLabel: "LAUNCHING",
    launchDate: "22 JUNE 2026",
    founderEyebrow: "FOUNDING MEMBER OFFER",
    founderHeadline: "First 500 subscribers join free, for life.",
    founderBody: "After the first 500, Reset Letters will cost £7 per month. But if you sign up before launch, you get everything. For ever. No catch.",
    ctaButtonLabel: "CLAIM MY FOUNDER PLACE",
    ctaPlaceholder: "your@email.com",
    ctaMicrocopy: "No spam. Honest writing. Cancel any time.",
  });

  // ═══ Decoder Page singleType (free lead-magnet page) — backfilled. 16 fields.
  await ensureSingleType(strapi, 'api::decoder-page.decoder-page', {
    whyBody: "",
    insideItems: "",
    heroEyebrow: "Free. Always free.",
    heroTitle: "The Nervous System Decoder.",
    heroTagline: "The first thing if you are new here.",
    coverLabel: "Free Guide",
    coverTitle: "The Nervous System Decoder",
    coverSubtitle: "A somatic self-audit, in seven quiet questions.",
    coverAuthor: "By Anna Lou Scaife",
    whyTitle: "Why this exists",
    insideTitle: "What's inside",
    formTitle: "Send it to me",
    formButtonLabel: "Send me the Decoder",
    formMicrocopy: "No spam. Unsubscribe in one click. We never share your email.",
    successTitle: "Your Decoder is on its way.",
    successBody: "Look for an email from Anna in the next few minutes. If it is not there, check spam or promotions.\n\nIn the meantime, if you want to go further, here is what comes next.",
  });

  // ═══ Menu-section landing-page singletypes — 6 main menu items get their own
  //     editable page so Anna controls every kicker/title/intro from CMS. Schema
  //     defaults already match the current hardcoded copy so seeding with empty
  //     objects materializes the entries with the right values. ═══
  await ensureSingleType(strapi, 'api::reset-stories-page.reset-stories-page', {});
  await ensureSingleType(strapi, 'api::life-page.life-page', {});
  await ensureSingleType(strapi, 'api::love-and-relationships-page.love-and-relationships-page', {});
  await ensureSingleType(strapi, 'api::work-and-money-page.work-and-money-page', {});
  await ensureSingleType(strapi, 'api::work-with-anna-page.work-with-anna-page', {});
  await ensureSingleType(strapi, 'api::shop-page.shop-page', {});

  // ═══ Site Settings — backfill fields added after the singleton was first
  //     created so Anna sees their default values rather than blank inputs.
  //     ensureSingleType only fills null/undefined/empty fields, so this is
  //     safe to re-run; Anna's edits are never overwritten. ═══
  await ensureSingleType(strapi, 'api::site-settings.site-settings', {
    max_subcategories_per_menu: 4,
    default_currency: 'GBP',
    supported_currencies: 'GBP, EUR, USD',
  });

  // ═══ Shop sub-pages — three sibling singletons under /shop/* ═══
  // Each was previously hardcoded inside its page.tsx; now CMS-editable
  // so Anna controls every paragraph and button label from admin.
  await ensureSingleType(strapi, 'api::shop-new-in-page.shop-new-in-page', {});
  await ensureSingleType(strapi, 'api::shop-personalised-page.shop-personalised-page', {});
  await ensureSingleType(strapi, 'api::shop-esj-page.shop-esj-page', {});

  // ═══ Quiz page — /the-work/quiz hero + 6 result blurbs ═══
  // Questions stay in code (complex weighted scoring matrix that Anna won't
  // tune by hand). Only the hero copy and the 6 result outcomes are CMS-
  // editable. Seed with exactly 6 results — one per slug the quiz routes to.
  await ensureSingleType(strapi, 'api::quiz-page.quiz-page', {
    results: [
      { slug: 'decoder', title: 'Start with the free Nervous System Decoder.', blurb: 'Before any programme, before any session, this is the foundation. Free guide. Seven self-audit questions. Three small practices to start with, today. It is the first thing offered to anyone who finds Anna Lou Wellness, because understanding your inner world is not a luxury, it is the foundation.', cta_label: 'Send me the free Decoder' },
      { slug: 'reset-room', title: 'The Reset Room is your room.', blurb: 'Monthly somatic membership for women doing the work on their own pace. Private podcast (two new episodes a month), monthly live call with Anna, growing vault of guided journeys. £25 a month, no minimum term. The slow, steady door. Cancel any time.', cta_label: 'Step into the Reset Room' },
      { slug: 'reset', title: 'The Reset is the right starting place.', blurb: 'A six-week 1:1 somatic coaching programme. Weekly 90-minute sessions with Anna. Nervous-system led, trauma-informed, designed to bring your signal system back online. £1,500. The door for women whose body is already telling them it is time.', cta_label: 'Read about The Reset' },
      { slug: 'signal', title: 'Signal is the right depth.', blurb: 'Twelve weeks of 1:1 work for a complete identity rewrite. Not a starter programme. For women already deep in the work who need depth, structure, and a coach who can hold the shape of a real transformation. Application required.', cta_label: 'Apply for Signal' },
      { slug: 'signal-build', title: 'Signal & Build is where business meets nervous system.', blurb: 'Twelve weeks of 1:1 work for the founder rebuilding her business from the body up. Strategy, somatic coaching, and a clear plan for the work that does not destroy you to maintain. Application required.', cta_label: 'Apply for Signal & Build' },
      { slug: 'one-day', title: 'One Day is the right reset.', blurb: 'A full 1:1 day with Anna. On the houseboat at Taggs Island, or in your space if you prefer. No calendar, no interruptions. Brought together for one specific decision, one specific weight, one specific moment of clarity. Enquire for pricing.', cta_label: 'Enquire about One Day' },
    ],
  });

  // ═══ Sessions hub — top-level /the-work/sessions page hero ═══
  // Cards on this page come from the Coaching Session collection (extended
  // with `tagline` + `accent_colour` fields so the card visuals are CMS-driven).
  // This singleton only holds the page-level hero copy.
  await ensureSingleType(strapi, 'api::sessions-hub-page.sessions-hub-page', {});

  // Back-fill tagline + accent_colour on existing coaching-session entries so
  // the /the-work/sessions card grid renders them on first paint. Idempotent —
  // only fills empties, never overwrites Anna's edits.
  const SESSION_DEFAULTS = [
    { slug: 'founder-reset', tagline: 'For the founder at a sticking point in the business or in herself.', accent_colour: '#FAA21B' },
    { slug: 'dating-reset', tagline: 'For the woman noticing the same pattern showing up again.', accent_colour: '#F280AA' },
    { slug: 'nervous-system-reset', tagline: 'For the woman whose signal system is scrambled and needs bringing back online.', accent_colour: '#7BAFDD' },
  ];
  for (const def of SESSION_DEFAULTS) {
    try {
      const existing = await strapi.documents('api::coaching-session.coaching-session').findFirst({ filters: { slug: def.slug } });
      if (!existing) continue;
      const patch = {};
      if (!existing.tagline) patch.tagline = def.tagline;
      if (!existing.accent_colour) patch.accent_colour = def.accent_colour;
      if (Object.keys(patch).length > 0) {
        await strapi.documents('api::coaching-session.coaching-session').update({ documentId: existing.documentId, data: patch });
      }
    } catch (err) {
      strapi.log.warn(`[seed-pages] coaching-session backfill failed for ${def.slug}: ${err.message}`);
    }
  }

  // ═══ Experiences landing — top-level /experiences page ═══
  // Was hardcoded with 4 category cards inline. Now editable as a singleton
  // with a repeatable categories component so Anna can reorder, rename, or
  // add a fifth card without touching code.
  await ensureSingleType(strapi, 'api::experiences-landing-page.experiences-landing-page', {
    categories: [
      { title: 'Retreats', description: 'A few times a year, a small group comes to Taggs Island, Hampton for a full reset day. Six people maximum. No phones, no fixed agenda. We work with whatever the group needs, breathwork, somatic practice, Signal Method, honest conversation. People arrive wound tight and leave softer.', href: '/experiences/retreats', colour: '#7BAFDD', link_label: 'View retreats' },
      { title: 'Workshops', description: 'Group sessions held on the houseboat at Taggs Island, online, and in corporate spaces. Every workshop includes full access or a recording and summary. Crystal healing, breathwork, jewellery-making, and restorative practices.', href: '/experiences/workshops', colour: '#7BAFDD', link_label: 'View workshops' },
      { title: 'Corporate Wellbeing', description: 'Bespoke formats for teams and organisations. Workshops, keynotes, and ongoing wellbeing programmes. The Signal Method adapted for corporate environments. Available in person or online.', href: '/experiences/corporate-wellbeing', colour: '#7BAFDD', link_label: 'Enquire' },
      { title: 'Speaking', description: 'Anna speaks on somatic coaching, the founder journey, nervous system regulation, and building a business from the body up. Available for conferences, panels, podcasts, and private events.', href: '/experiences/speaking', colour: '#7BAFDD', link_label: 'Enquire' },
    ],
  });

  // ═══ About Page — seed press logos + certifications as components ═══
  // Schema converted these from JSON to repeatable components so Anna can edit
  // through a form (with image upload per row) instead of raw JSON. Pre-populate
  // with the current names so the structure is visible from day one.
  await ensureSingleType(strapi, 'api::about-page.about-page', {
    press_logos: [
      { name: 'Harrods' },
      { name: 'Selfridges' },
      { name: 'Harvey Nichols' },
      { name: 'Liberty' },
      { name: 'QVC Japan' },
      { name: 'Disney' },
      { name: 'The Telegraph' },
      { name: 'Stylist' },
    ],
    certifications: [
      { name: 'ICF\nCertified Coach', colour: '#6E3A5A' },
      { name: 'CPD\nAccredited', colour: '#7BAFDD' },
      { name: 'TRE®\nProvider', colour: '#5DCAA5' },
    ],
  });

  // ═══ Community Page — seed Reset Room features as components ═══
  await ensureSingleType(strapi, 'api::community-page.community-page', {
    reset_room_features: [
      { text: 'Live monthly Reset Call with Anna (90 minutes)' },
      { text: 'Full Resource Library — workshop replays, founder resets, paid archive' },
      { text: 'Members-only events, seasonal resets, in-person houseboat days' },
      { text: 'First access to new retreats (48 hours before public)' },
      { text: '10% off all 1:1 work' },
    ],
  });

  // ═══ Membership — seed features as components (in addition to other defaults) ═══
  // Note: this won't overwrite the existing membership singleType seed above; ensureSingleType
  // only backfills empty fields. Calling again just to populate the new features field.
  await ensureSingleType(strapi, 'api::membership.membership', {
    features: [
      { text: 'Live monthly Reset Call with Anna' },
      { text: 'Full Resource Library access' },
      { text: 'Members-only events' },
      { text: 'First access to new retreats' },
      { text: '10% off 1:1 work' },
    ],
  });

  // ═══ Navigation singleType — Anna edits all menus + sub-menus here ═══
  // Seeded with the current site.ts fallback so the first admin page-load
  // shows the live nav rather than an empty form. The frontend reads this
  // singleType at request time (cached) and falls back to site.ts if Strapi
  // is unreachable, so editing here is the source of truth going forward.
  await ensureSingleType(strapi, 'api::navigation.navigation', {
    top_strip_text: 'Stories · Work with Anna · Experiences · Shop · Community',
    items: [
      {
        __component: 'nav.menu-item',
        label: 'Reset Stories',
        href: '/reset-stories',
        colour: '#6E3A5A',
        children: [
          { __component: 'nav.child-link', label: 'All Stories', href: '/reset-stories' },
          { __component: 'nav.child-link', label: 'Holding Everything', href: '/reset-stories/holding-everything' },
          { __component: 'nav.child-link', label: 'The Strong One', href: '/reset-stories/the-strong-one' },
          { __component: 'nav.child-link', label: 'Signal vs Noise', href: '/reset-stories/signal-vs-noise' },
          { __component: 'nav.child-link', label: 'Houseboat Life', href: '/life/houseboat-life' },
          { __component: 'nav.child-link', label: 'Spiritual Hygiene', href: '/life/spiritual-hygiene' },
        ],
      },
      {
        __component: 'nav.menu-item',
        label: 'Life',
        href: '/life',
        colour: '#FAA21B',
        children: [
          { __component: 'nav.child-link', label: 'Rituals and Energy', href: '/life/rituals-and-energy' },
          { __component: 'nav.child-link', label: 'Home and Space', href: '/life/home-and-space' },
          { __component: 'nav.child-link', label: 'Style and Beauty', href: '/life/style-and-beauty' },
          { __component: 'nav.child-link', label: 'Food and Nourishment', href: '/life/food-and-nourishment' },
        ],
      },
      {
        __component: 'nav.menu-item',
        label: 'Love & Relationships',
        href: '/love-and-relationships',
        colour: '#F280AA',
        children: [
          { __component: 'nav.child-link', label: 'Dating and Patterns', href: '/love-and-relationships/dating-and-patterns' },
          { __component: 'nav.child-link', label: 'Breakups and Reset', href: '/love-and-relationships/breakups-and-reset' },
          { __component: 'nav.child-link', label: 'Friendship', href: '/love-and-relationships/friendship' },
          { __component: 'nav.child-link', label: 'Motherhood', href: '/love-and-relationships/motherhood' },
          { __component: 'nav.child-link', label: 'Self Worth and Identity', href: '/love-and-relationships/self-worth-and-identity' },
        ],
      },
      {
        __component: 'nav.menu-item',
        label: 'Work & Money',
        href: '/work-and-money',
        colour: '#FFD07A',
        children: [
          { __component: 'nav.child-link', label: 'Founder Reset', href: '/work-and-money/founder-reset' },
          { __component: 'nav.child-link', label: 'Burnout and Nervous System', href: '/work-and-money/burnout-and-nervous-system' },
          { __component: 'nav.child-link', label: 'Career and Direction', href: '/work-and-money/career-and-direction' },
          { __component: 'nav.child-link', label: 'Money and Worth', href: '/work-and-money/money-and-worth' },
        ],
      },
      {
        __component: 'nav.menu-item',
        label: 'Experiences',
        href: '/experiences',
        colour: '#7BAFDD',
        children: [
          { __component: 'nav.child-link', label: 'Retreats', href: '/experiences/retreats' },
          { __component: 'nav.child-link', label: 'Workshops', href: '/experiences/workshops' },
          { __component: 'nav.child-link', label: 'Corporate Wellbeing', href: '/experiences/corporate-wellbeing' },
          { __component: 'nav.child-link', label: 'Speaking', href: '/experiences/speaking' },
        ],
      },
      {
        __component: 'nav.menu-item',
        label: 'Work with Anna',
        href: '/the-work',
        colour: '#F280AA',
        children: [
          { __component: 'nav.child-link', label: 'Take the Quiz', href: '/the-work/quiz' },
          { __component: 'nav.child-link', label: 'The Reset · 6 weeks', href: '/the-work/the-reset' },
          { __component: 'nav.child-link', label: 'Signal · 12 weeks', href: '/the-work/signal' },
          { __component: 'nav.child-link', label: 'Signal & Build · Founders', href: '/the-work/signal-and-build' },
          { __component: 'nav.child-link', label: 'One Day · Intensive', href: '/the-work/one-day' },
          { __component: 'nav.child-link', label: 'Signal Collective · Mastermind', href: '/the-work/signal-collective' },
          { __component: 'nav.child-link', label: '1:1 Reset Sessions', href: '/the-work/sessions' },
          { __component: 'nav.child-link', label: 'Recovery Coaching', href: '/the-work/recovery' },
          { __component: 'nav.child-link', label: 'Client Stories', href: '/the-work/client-stories' },
        ],
      },
      {
        __component: 'nav.menu-item',
        label: 'Shop',
        href: '/shop',
        colour: '#5DCAA5',
        children: [
          { __component: 'nav.child-link', label: 'All Jewellery', href: '/shop' },
          { __component: 'nav.child-link', label: 'Emotional Support Jewellery', href: '/shop/emotional-support-jewellery' },
          { __component: 'nav.child-link', label: 'Personalised Pieces', href: '/shop/personalised' },
          { __component: 'nav.child-link', label: 'New In', href: '/shop/new-in' },
        ],
      },
      {
        __component: 'nav.menu-item',
        label: 'Community',
        href: '/community',
        colour: '#231F20',
        children: [
          { __component: 'nav.child-link', label: 'The Returning Circle', href: '/community/the-returning-circle' },
          { __component: 'nav.child-link', label: 'The Reset Room', href: '/community/reset-room' },
          { __component: 'nav.child-link', label: 'Events Calendar', href: '/community/events' },
          { __component: 'nav.child-link', label: 'Resource Library', href: '/community/resources' },
        ],
      },
      {
        __component: 'nav.menu-item',
        label: 'About',
        href: '/about',
        colour: '#231F20',
        children: [
          { __component: 'nav.child-link', label: "Anna's Story", href: '/about' },
          { __component: 'nav.child-link', label: 'Press', href: '/about/press' },
          { __component: 'nav.child-link', label: 'Work With Me', href: '/about/partnerships' },
          { __component: 'nav.child-link', label: 'Contact', href: '/contact' },
        ],
      },
    ],
  });

  // ═══ Experience pages ═══
  await ensure(strapi, 'api::experience-page.experience-page', 'workshops', {
    title: 'Workshops',
    kicker: 'Experiences',
    kickerColour: '#7BAFDD',
    intro: [
      'Group sessions held on the houseboat at Taggs Island, online, and in corporate spaces. Every workshop includes either full access or a recording and summary so you can engage at whatever level feels right.',
      'Workshops combine somatic practice, breathwork, and honest conversation in an immersive format designed to help you maintain resilience.',
      'Surrendering and Raising Your Vibration is a regular online workshop focused on releasing tension patterns and reconnecting with your body’s natural energy.',
      'All workshop recordings are available in the Reset Room resource library for members.',
    ].join('\n\n'),
    ctaLabel: 'View upcoming workshops',
    ctaUrl: '/community/events',
  });

  await ensure(strapi, 'api::experience-page.experience-page', 'retreats', {
    title: 'Retreats',
    kicker: 'Experiences',
    kickerColour: '#7BAFDD',
    intro: [
      'A few times a year, a small group comes to Taggs Island, Hampton for a full reset day. Six people maximum. No phones, no fixed agenda.',
      'We work with whatever the group needs — breathwork, somatic practice, the Signal Method™, honest conversation. People arrive wound tight and leave softer.',
      'The houseboat is surrounded by water on all sides. There is something about being on the river that strips away everything that is not real. The space itself does half the work.',
      'Each retreat includes a full day of guided practice, lunch prepared on the houseboat, and a take-home integration guide.',
      'Retreats are announced to the mailing list first. Sign up to Reset Letters for priority access.',
    ].join('\n\n'),
    ctaLabel: 'Register interest',
    ctaUrl: '/contact',
  });

  await ensure(strapi, 'api::experience-page.experience-page', 'corporate-wellbeing', {
    title: 'Corporate Wellbeing.',
    kicker: 'Experiences · For teams',
    kickerColour: '#7BAFDD',
    intro: [
      'Bespoke formats for teams and organisations. Workshops, keynotes, and ongoing wellbeing programmes tailored to your workplace. The Signal Method adapted for corporate environments.',
      'Formats range from a single 90-minute session to a full-day immersive experience. Available in person at your workplace, on the houseboat at Taggs Island, or online.',
      'Anna brings fifteen years of entrepreneurial experience and clinical somatic training to every corporate engagement. This is not generic mindfulness. This is nervous system work that actually changes how people show up.',
    ].join('\n\n'),
    secondaryList: [
      '90-minute session|A single workshop. Online or in person. Topic shaped to your team.',
      'Half-day or full-day|Immersive teambuilding plus nervous system regulation. On houseboat or at your space.',
      'Keynote / panel|For conferences and offsites. Up to 200 attendees.',
      'Ongoing programme|Quarterly or monthly cadence. Depth over time. Bespoke design.',
    ].join('\n'),
  });

  await ensure(strapi, 'api::experience-page.experience-page', 'speaking', {
    title: 'Speaking.',
    kicker: 'Experiences · For events',
    kickerColour: '#FAA21B',
    intro: [
      'Anna speaks on the inner guidance system, the nervous system, somatic coaching, the recovery work that follows narcissistic abuse, and what it actually takes for a woman to rebuild from burnout. She also speaks to founders on the link between the body and the business.',
      'Format depends on what your audience needs. Keynote, panel, fireside, intimate Q&A. Online or in the room.',
    ].join('\n\n'),
    secondaryList: [
      'The Inner Guidance System.|What it is, how it gets scrambled, how to bring it back online.',
      'Burnout is a nervous system event.|The biology of what happens, and why willpower will not fix it.',
      'Recovering from narcissistic abuse.|Honest, somatic, no jargon. For survivors and the people supporting them.',
      'The body knows first.|Why founder decisions made from a dysregulated body are almost always wrong.',
      "The Signal Method.|A framework for living and leading from your own signal, not someone else's noise.",
    ].join('\n'),
  });

  // ═══ Individual Experience entries (Anna's currently-selling products) ═══
  // Migrated from the legacy WooCommerce shop on annalouwellness.com.
  // Anna can edit these in Strapi → Work · Experience. Dates and prices match
  // what she was actively selling as of 22 May 2026; she will roll new dates
  // here as she announces them. Hero images intentionally not seeded — Anna
  // uploads via the CMS so they land in Cloudinary with correct EXIF rotation.
  const houseboatResetDescription = [
    'A one-day somatic experience on the water. Step out of the noise, reconnect to your body, and return to a steadier, clearer way of being.',
    'The day includes conscious connected breathwork and sacral activation, surrender and release rituals with flash EMDR and tapping, body-based work with pendulum guidance, and a somatic closing ceremony.',
    'You receive chai on arrival, ceremonial cacao, an alkaline lunch in the island garden, and all materials needed for the sessions. A pendulum is provided if you don\'t have one.',
    'You leave with a genuine nervous system reset, subconscious loops named and released, clarity on the next aligned move, and body trust restored. Six places maximum.',
    'Arrive from 9.00am for tea on the deck. Day runs 10.00am to 4.00pm.',
  ].join('\n\n');

  await ensure(strapi, 'api::experience.experience', 'houseboat-reset-2026-06-13', {
    name: 'Houseboat Nervous System Reset · 13 June',
    type: 'retreat',
    description: houseboatResetDescription,
    date: '2026-06-13',
    location: 'Taggs Island, Half Mile, Hampton, TW12 2HA',
    price: 115.00,
    price_label: '£115 · Day immersion',
    is_upcoming: true,
    is_active: true,
    sort_order: 10,
    seo_title: 'Houseboat Nervous System Reset — 13 June',
    seo_description: 'One-day somatic retreat on the Thames at Taggs Island. Breathwork, EMDR, somatic release. £115. Six places.',
  });

  await ensure(strapi, 'api::experience.experience', 'houseboat-reset-2026-06-27', {
    name: 'Houseboat Nervous System Reset · 27 June',
    type: 'retreat',
    description: houseboatResetDescription,
    date: '2026-06-27',
    location: 'Taggs Island, Half Mile, Hampton, TW12 2HA',
    price: 115.00,
    price_label: '£115 · Day immersion',
    is_upcoming: true,
    is_active: true,
    sort_order: 20,
    seo_title: 'Houseboat Nervous System Reset — 27 June',
    seo_description: 'One-day somatic retreat on the Thames at Taggs Island. Breathwork, EMDR, somatic release. £115. Six places.',
  });

  await ensure(strapi, 'api::experience.experience', 'houseboat-reset-2026-07-18', {
    name: 'Houseboat Nervous System Reset · 18 July',
    type: 'retreat',
    description: houseboatResetDescription,
    date: '2026-07-18',
    location: 'Taggs Island, Half Mile, Hampton, TW12 2HA',
    price: 115.00,
    price_label: '£115 · Day immersion',
    is_upcoming: true,
    is_active: true,
    sort_order: 30,
    seo_title: 'Houseboat Nervous System Reset — 18 July',
    seo_description: 'One-day somatic retreat on the Thames at Taggs Island. Breathwork, EMDR, somatic release. £115. Six places.',
  });

  await ensure(strapi, 'api::experience.experience', 'houseboat-reset-2026-07-25', {
    name: 'Houseboat Nervous System Reset · 25 July',
    type: 'retreat',
    description: houseboatResetDescription,
    date: '2026-07-25',
    location: 'Taggs Island, Half Mile, Hampton, TW12 2HA',
    price: 115.00,
    price_label: '£115 · Day immersion',
    is_upcoming: true,
    is_active: true,
    sort_order: 40,
    seo_title: 'Houseboat Nervous System Reset — 25 July',
    seo_description: 'One-day somatic retreat on the Thames at Taggs Island. Breathwork, EMDR, somatic release. £115. Six places.',
  });

  await ensure(strapi, 'api::experience.experience', 'align-and-amplify', {
    name: 'Align & Amplify · A One-Day Immersion in THE CODES',
    type: 'workshop',
    description: [
      'An exclusive one-day immersion anchored in THE CODES — Anna\'s signature framework for decoding subconscious blocks and aligning with your unique essence.',
      'Led personally by Anna Lou, drawing from 25 years scaling a 7-figure jewellery brand. Hosted on a private houseboat on the Thames at Taggs Island. Seven places maximum.',
      'The day includes a ceremonial cacao opening, somatic nervous system regulation, conscious connected breathwork, pendulum guidance, TRE tension release, and subconscious pattern work.',
      'You leave with a nervous system reset, subconscious loops released, and one clear next direction your system trusts.',
      'Day runs 10.00am to 4.00pm. Next available date confirmed on enquiry.',
    ].join('\n\n'),
    date: '2026-06-20',
    location: 'Taggs Island, Hampton (private houseboat on the Thames)',
    price: 90.00,
    price_label: '£90 · Day immersion',
    is_upcoming: true,
    is_active: true,
    sort_order: 50,
    seo_title: 'Align & Amplify — One-Day Immersion in THE CODES',
    seo_description: 'One-day immersion in Anna\'s CODES framework. Breathwork, somatic regulation, pattern work. £90. Seven places.',
  });

  await ensure(strapi, 'api::experience.experience', 'returning-circle-class', {
    name: 'The Returning Circle · Learn the Language of Your Nervous System',
    type: 'workshop',
    description: [
      'An intimate 60-minute session designed to help you understand your nervous system and develop practical self-regulation tools. Pay what you can afford.',
      'The class combines TRE (Trauma Release Experience) with gentle tremor work, conscious connected breathwork, chakra opening meditation, and nervous system education.',
      'You learn to recognise the signals your body is sending you and respond to them with compassion instead of override. Suitable if you feel disconnected from your body, want to understand your patterns, or just want practical tools for self-regulation.',
      'No prior experience required. Runs weekly, Tuesdays 2.00pm to 3.00pm.',
    ].join('\n\n'),
    date: '2026-05-26',
    location: 'Online (Zoom)',
    price: 5.55,
    price_label: '£5.55 · Pay what you can',
    is_upcoming: true,
    is_active: true,
    sort_order: 60,
    seo_title: 'The Returning Circle — Weekly Nervous System Class',
    seo_description: 'Weekly 60-min online class. TRE, breathwork, chakra meditation. Pay what you can afford, from £5.55.',
  });

  await ensure(strapi, 'api::experience.experience', 'rise-and-shine-7-figures', {
    name: 'Rise and Shine · To Get to 7 Figures',
    type: 'workshop',
    description: [
      'A powerful day session on the houseboat for leaders and entrepreneurs ready to elevate their business.',
      'The day challenges the societal narratives about success and emphasises that seven-figure achievement is within reach when you are willing to embrace your full potential.',
      'You engage in somatic practices, breathwork journeys, crystal energy work, and vulnerability release exercises. The focus is on becoming a powerful entrepreneur who honours her own needs, reduces stress, and pursues ambitious goals without sacrifice.',
      'For driven women who refuse to settle and are committed to rewriting the rules of leadership and entrepreneurship.',
      'Day runs 10.00am to 4.00pm.',
    ].join('\n\n'),
    date: '2026-07-04',
    location: 'Taggs Island, Half Mile, Hampton, TW12 2HA',
    price: 90.00,
    price_label: '£90 · Day session',
    is_upcoming: true,
    is_active: true,
    sort_order: 70,
    seo_title: 'Rise and Shine — Get to 7 Figures (Houseboat Day Session)',
    seo_description: 'One-day session for women entrepreneurs on the houseboat. Somatic work, breathwork, vulnerability release. £90.',
  });

  // ═══ One-shot cleanup: delete known placeholder Experience entries ═══
  // These were demo data seeded before Anna's real WooCommerce migration.
  // They confuse the admin list and don't represent real bookable events.
  // Delete is by exact slug — if Anna later creates an event with the same
  // slug intentionally, she will need to use a different name (unlikely).
  const PLACEHOLDER_EXPERIENCE_SLUGS = [
    'autumn-reset-day',
    'surrendering-vibration',
    'surrendering-and-raising-your-vibration',
  ];
  for (const slug of PLACEHOLDER_EXPERIENCE_SLUGS) {
    try {
      const found = await strapi.documents('api::experience.experience').findMany({
        filters: { slug },
        limit: 1,
      });
      if (found && found.length > 0) {
        await strapi.documents('api::experience.experience').delete({
          documentId: found[0].documentId,
        });
        strapi.log.info(`[seed-pages] Deleted placeholder Experience: ${slug}`);
      }
    } catch (err) {
      strapi.log.warn(`[seed-pages] Skipped placeholder delete (${slug}): ${err.message}`);
    }
  }

  // ═══ Normalize sort_order on Experience entries by date ═══
  // Anna's admin list view sorts by sort_order. Without normalization, the
  // numbers are arbitrary (old seeds used 10/20/30, placeholders use 1/2)
  // and the list looks random. After every boot we recompute sort_order so
  // it matches date ASC — soonest event at sort_order 10, next at 20, etc.
  // Gaps of 10 leave room for Anna to manually insert in between if she ever
  // wants to override (but next boot will renormalize).
  try {
    const all = await strapi.documents('api::experience.experience').findMany({
      pagination: { pageSize: 100 },
    });
    const byDateAsc = [...all].sort((a, b) => {
      const da = a.date || '9999-12-31';
      const db = b.date || '9999-12-31';
      return da.localeCompare(db);
    });
    let updates = 0;
    for (let i = 0; i < byDateAsc.length; i++) {
      const e = byDateAsc[i];
      const wanted = (i + 1) * 10;
      if (e.sort_order !== wanted) {
        await strapi.documents('api::experience.experience').update({
          documentId: e.documentId,
          data: { sort_order: wanted },
          status: 'published',
        });
        updates++;
      }
    }
    if (updates > 0) {
      strapi.log.info(`[seed-pages] Normalized sort_order on ${updates} Experience entries by date`);
    }
  } catch (err) {
    strapi.log.warn(`[seed-pages] Skipped Experience sort_order normalization: ${err.message}`);
  }

  // ═══ Community Event pages ═══
  await ensure(strapi, 'api::community-event-page.community-event-page', 'the-returning-circle', {
    title: 'The Returning Circle.',
    kicker: 'Community · Weekly · Donation-based',
    kickerColour: '#5DCAA5',
    intro: [
      'Every Wednesday evening Anna holds a circle. Hybrid. In person on the houseboat at Taggs Island for those who can travel. Live on Zoom for everyone else.',
      'What it is: a room. People who are honest. No advice. No fixing. No cross-talk. Just being in the presence of other humans who are willing to say what is actually going on.',
      'What it is not: therapy, a support group, a workshop, or anything with a curriculum. There is no programme. There is no progression. You come when you need to. You stop when you are done.',
    ].join('\n\n'),
    ctaLabel: 'Hold a place',
    ctaUrl: '#rsvp',
  });

  await ensure(strapi, 'api::community-event-page.community-event-page', 'events', {
    title: 'Events Calendar',
    kicker: 'Community',
    kickerColour: '#231F20',
    intro: [
      'All upcoming events in one place. Retreats on Taggs Island, workshops (online and in person), and member-only Reset Room sessions.',
      'For bespoke corporate events and private bookings, please get in touch directly.',
    ].join('\n\n'),
    ctaLabel: 'Enquire about events',
    ctaUrl: '/contact',
  });

  // ═══ Generic pages ═══
  await ensure(strapi, 'api::generic-page.generic-page', 'about-press', {
    title: 'Press',
    kicker: 'About',
    kickerColour: '#231F20',
    intro: [
      'Twenty-five years of press coverage. From the first piece about someone selling handmade jewellery on Portobello Road, to Harrods, Selfridges, Liberty, Harvey Nichols, QVC Japan, Disney, and Henri Bendel New York.',
      'For most of those years the press was about the brand and the jewellery. More recently the coverage has shifted. The coaching, the houseboat, the pivot.',
      'Anna holds ICF coaching accreditation, CPD certification, and is a certified TRE® provider. She is a somatic trauma-informed coach specialising in nervous system regulation and healing from narcissistic abuse.',
      'For press enquiries, interviews, podcast appearances, and media features, please contact hello@annalouwellness.com.',
    ].join('\n\n'),
    ctaLabel: 'Press enquiries',
    ctaUrl: '/contact',
  });

  await ensure(strapi, 'api::generic-page.generic-page', 'about-partnerships', {
    title: 'Work With Me',
    kicker: 'About',
    kickerColour: '#231F20',
    intro: [
      "Anna Lou Wellness is open to collaborations that align with the brand's values: honest storytelling, somatic wellbeing, ethical production, and supporting women through real transformation.",
      'Previous collaborations include Harrods, Selfridges, Harvey Nichols, Liberty, Disney, Hello Kitty, Ray-Ban, QVC Japan, and a range of independent retailers worldwide.',
      'We are interested in brand partnerships, product collaborations, editorial sponsorships, and event co-hosting. If what you do supports women coming back to themselves, we want to hear from you.',
      'For all enquiries, please email hello@annalouwellness.com with a brief outline of what you have in mind.',
    ].join('\n\n'),
    ctaLabel: 'Get in touch',
    ctaUrl: '/contact',
  });

  await ensure(strapi, 'api::generic-page.generic-page', 'the-work-client-stories', {
    title: 'Client Stories',
    kicker: 'Work with Anna',
    kickerColour: '#F280AA',
    intro: [
      'These are not testimonials. They are editorial pieces — real stories from real clients about what happens when you come home to yourself.',
      '“The thing about Anna is she doesn’t let you stay comfortable. Not in a confrontational way. In a way where your body suddenly shows you what you’ve been avoiding, and you realise you’re ready.” — Claudine, London',
      '“I thought I needed a business coach. Turns out I needed someone who could see that my nervous system was making every business decision for me.” — Susan, New York',
      'More stories are coming. If you have worked with Anna and would like to share your experience, please get in touch.',
    ].join('\n\n'),
    ctaLabel: 'Start your story',
    ctaUrl: '/contact',
  });

  await ensure(strapi, 'api::generic-page.generic-page', 'the-work-ways-to-work-with-me', {
    title: 'Ways to Work With Me',
    kicker: 'Work with Anna',
    kickerColour: '#F280AA',
    intro: [
      'The Signal Method™ is the umbrella for all the coaching work here. It is a somatic framework Anna developed from fifteen years of personal practice and clinical training.',
      'Underneath it sit the programmes, each designed for a different stage of the journey. Whether you are just beginning to notice the patterns, or you are ready to rewire them completely, there is a way in.',
      'The Reset (6 weeks, £1,500) — The starting point. Identify and begin releasing the patterns running your life.',
      'Signal (12 weeks, £3,000) — The deep dive. For women ready to rewire at a deeper level.',
      'Signal & Build (12 weeks, £3,000) — Signal plus business coaching. For founders whose nervous system is affecting their business.',
      'One Day Intensive (enquire) — A full day on the houseboat. Immersive, concentrated work.',
      'The Signal Collective (by application) — Ongoing mastermind for women who have completed a programme and want continued support.',
      'Not sure which is right? Book a free 15-minute discovery call.',
    ].join('\n\n'),
    ctaLabel: 'Book a discovery call',
    ctaUrl: '/contact',
  });

  // ═══ Programmes (Reset Sessions + Recovery + Signal Collective) ═══
  await ensure(strapi, 'api::programme.programme', 'founder-reset', {
    title: 'Founder Reset',
    tagline: 'For the founder at a sticking point in the business or in herself.',
    accentColour: '#FAA21B',
    intro: 'Most founder problems are not strategy problems. They are capacity problems wearing strategy clothes. A Founder Reset is the session where we work out which one yours is, and we move it.',
    pricingLabel: 'Investment',
    pricingBody: '£200, paid at booking. 90 minutes, virtual.',
    ctaLabel: 'Book this session',
    ctaUrl: '/contact',
    pricePence: 20000,
    currency: 'gbp',
    isRecurring: false,
    mailchimpTag: 'Reset Session (90-min)',
    grantsResetRoomAccess: false,
  });

  await ensure(strapi, 'api::programme.programme', 'dating-reset', {
    title: 'Dating Reset',
    tagline: 'For the woman noticing the same pattern showing up again.',
    accentColour: '#F280AA',
    intro: 'Dating Reset is for the woman who has noticed the same pattern showing up again and is ready to ask why. We do not do dating tips. We do the underneath. The patterns, the attachment shape, the unfinished business with the version of love you grew up with.',
    pricingLabel: 'Investment',
    pricingBody: '£200, paid at booking. 90 minutes, virtual.',
    ctaLabel: 'Book this session',
    ctaUrl: '/contact',
    pricePence: 20000,
    currency: 'gbp',
    isRecurring: false,
    mailchimpTag: 'Reset Session (90-min)',
    grantsResetRoomAccess: false,
  });

  await ensure(strapi, 'api::programme.programme', 'nervous-system-reset', {
    title: 'Nervous System Reset',
    tagline: 'For the woman whose signal system is scrambled and needs bringing back online.',
    accentColour: '#7BAFDD',
    intro: 'Nervous System Reset is for the woman whose body has been holding the line for a long time and has started to lose the signal. We do not talk it out. We work with what is happening in the body, gently and slowly, and we bring the signal back online.',
    pricingLabel: 'Investment',
    pricingBody: '£200, paid at booking. 90 minutes, virtual.',
    ctaLabel: 'Book this session',
    ctaUrl: '/contact',
    pricePence: 20000,
    currency: 'gbp',
    isRecurring: false,
    mailchimpTag: 'Reset Session (90-min)',
    grantsResetRoomAccess: false,
  });

  await ensure(strapi, 'api::programme.programme', 'recovery', {
    title: 'Untangle. Unbind. Unbound.',
    tagline: 'Three months to reclaim yourself, permanently.',
    accentColour: '#6E3A5A',
    intro: [
      'Gaslighting does not just confuse your thinking. It dismantles your ability to trust your own body. The signals that used to tell you something is wrong — the tightening in your chest, the instinct to leave the room, the quiet voice that says this is not right — those signals get systematically overridden until you cannot hear them at all.',
      'What remains is hypervigilance. Freeze. Fawn. A nervous system permanently scanning for threat, even years after the relationship has ended. The body-level residue of narcissistic abuse is not a mindset problem. It is a nervous system injury.',
      'This is why talk therapy alone often is not enough. You can understand what happened intellectually and still feel the activation in your body every time you hear a particular tone of voice or walk into a room with a certain energy.',
      'Somatic coaching works at the level where the damage actually lives. In the body. In the automatic responses. In the nervous system patterns that were rewired by someone who needed you to doubt yourself.',
    ].join('\n\n'),
    stagesList: [
      'Month One|Untangle.|Somatic mapping, breathwork, Flash EMDR for specific traumatic memories. We identify where the patterns live in the body and begin to separate your responses from the ones that were installed by someone else.',
      'Month Two|Unbind.|TRE for trauma release, Internal Family Systems parts work, boundary recalibration. The parts of you that learned to fawn, freeze, or fight begin to find new options. Your boundaries stop being theoretical and become felt.',
      'Month Three|Unbound.|Integration, intuition strengthening, personal recovery map. The signal comes back. You start hearing your own body again. By month three something genuine has shifted, not at the level of insight but at the level of automatic response.',
    ].join('\n'),
    pricingLabel: 'Investment',
    pricingBody: 'By enquiry. Anna shapes the price to your situation. Payment plans available. Some places held at reduced rate for women genuinely unable to pay full price.',
    ctaLabel: 'Send a private enquiry',
    ctaUrl: '#enquire',
    pricePence: 0,
    currency: 'gbp',
    isRecurring: false,
    mailchimpTag: '',
    grantsResetRoomAccess: false,
  });

  await ensure(strapi, 'api::programme.programme', 'signal-collective', {
    title: 'The Signal Collective.',
    tagline: 'The inner work, in community. Six months.',
    accentColour: '#6E3A5A',
    intro: [
      'The Signal Collective is the mastermind. For coaches, founders, practitioners, and leaders who want depth plus community. Group and 1:1 coaching combined. Monthly intensive sessions. Peer co-regulation with people at the same level of seriousness. Direct access to the Signal Method applied to everything: business, relationships, creative work, leadership.',
      'A curated community committed to operating from their highest level. Not a course. A container for those already in motion who want to accelerate.',
    ].join('\n\n'),
    pricingLabel: 'Investment',
    pricingBody: 'By enquiry. Application form first, then a discovery call.',
    ctaLabel: 'Apply',
    ctaUrl: '#apply',
    pricePence: 0,
    currency: 'gbp',
    isRecurring: false,
    mailchimpTag: 'Signal Collective',
    grantsResetRoomAccess: false,
  });

  await ensure(strapi, 'api::programme.programme', 'the-reset', {
    title: 'The Reset.',
    tagline: 'Six weeks. One-to-one. Signal back online.',
    accentColour: '#F280AA',
    intro: [
      'Most people arrive at The Reset after trying everything else. The therapy. The journalling. The courses. The spiritual work. Getting all the way to the insight, and then hitting the same wall.',
      'The Reset is six weeks, 1:1, working directly with your inner guidance system. Not the story. Not the intellectual understanding of the pattern. The actual place the pattern lives, in the body, in the automatic responses that fire before your conscious mind catches up.',
      'Most of us spend years trying to fight the current. The Reset is the work of learning to stop gripping. Because when you stop gripping you realise the river was always guiding you. Your inner guidance system was never broken. It was waiting for you to stop overriding it.',
      'Week one: baseline. Where are you arriving from? What is your inner world doing right now? What does safety feel like in your body, and how long since you genuinely felt it?',
      'By week three something usually shifts. A decision becomes clear. A pattern stops activating the same response.',
    ].join('\n\n'),
    whatsIncludedLabel: "What's included",
    whatsIncludedItems: [
      'Six 1:1 sessions, weekly, 60 minutes each',
      'Voxer support between sessions, Tuesday to Thursday',
      'Starting audit of your inner world',
      'Tools that fit your actual life',
      'A clear close at week six. Many clients roll into Signal. Many do not need to.',
    ].join('\n'),
    pricingLabel: 'Investment',
    pricingBody: '£1,500. Paid in full at booking, or two instalments of £750 across the six weeks. If you are not sure, book a free fifteen-minute discovery call.',
    ctaLabel: 'Book a discovery call',
    ctaUrl: '/contact',
    pricePence: 150000,
    currency: 'gbp',
    isRecurring: false,
    mailchimpTag: 'The Reset (6-week)',
    grantsResetRoomAccess: false,
    displayOrder: 10,
  });

  await ensure(strapi, 'api::programme.programme', 'signal', {
    title: 'Signal.',
    tagline: 'Twelve weeks. One-to-one. The deeper container.',
    accentColour: '#6E3A5A',
    intro: [
      'Twelve weeks is enough time for something to genuinely change. Not the surface, the pattern underneath it. The automatic response that has been running your decisions, your relationships, and your relationship to yourself without your full permission.',
      'Signal is the full twelve-week somatic coaching programme. Inner world rewire, pattern release, belief repatterning, rebuilding from the inside out. Weekly sessions, integration support throughout.',
    ].join('\n\n'),
    whatsIncludedLabel: "What's included",
    whatsIncludedItems: [
      'Twelve 1:1 sessions, weekly, 60 minutes each',
      'Voxer support Tuesday to Thursday',
      'Personalised Signal Method workbook',
      'Lifetime access to recordings',
      'Optional in-person session at the Hampton studio',
    ].join('\n'),
    pricingLabel: 'Investment',
    pricingBody: '£3,000. Paid in full, or three instalments of £1,000.',
    ctaLabel: 'Book a discovery call',
    ctaUrl: '/contact',
    pricePence: 300000,
    currency: 'gbp',
    isRecurring: false,
    mailchimpTag: 'Signal (12-week)',
    grantsResetRoomAccess: false,
    displayOrder: 20,
  });

  await ensure(strapi, 'api::programme.programme', 'signal-and-build', {
    title: 'Signal & Build.',
    tagline: 'Twelve weeks. The inner work and the business, held together.',
    accentColour: '#FAA21B',
    intro: [
      'Signal & Build is Signal with a second track: heart-led business strategy using the Signal Method. For founders, coaches, and leaders who want to regulate their inner world and build from that place.',
    ].join('\n\n'),
    whatsIncludedLabel: "What's included",
    whatsIncludedItems: [
      'Everything in Signal: twelve 1:1 sessions, Voxer support, full inner-world audit',
      'Business strategy sessions interleaved with the inner work — pricing, positioning, capacity, decision-making, team, founder energy',
      'Drawn from twenty years building Anna Lou of London across Harrods, Selfridges, Liberty, Harvey Nichols',
      'Voxer access widened to include in-the-moment business questions',
    ].join('\n'),
    pricingLabel: 'Investment',
    pricingBody: '£3,000. Paid in full, or three instalments of £1,000.',
    ctaLabel: 'Book a discovery call',
    ctaUrl: '/contact',
    pricePence: 300000,
    currency: 'gbp',
    isRecurring: false,
    mailchimpTag: 'Signal & Build (founders)',
    grantsResetRoomAccess: false,
    displayOrder: 25,
  });

  await ensure(strapi, 'api::programme.programme', 'one-day', {
    title: 'One Day.',
    tagline: 'A full day. Held, focused, finished.',
    accentColour: '#5DCAA5',
    intro: [
      'One Day is exactly that. A full day, 1:1, on the houseboat at Taggs Island or online. No multi-week commitment. One concentrated, unhurried, immersive day.',
      'We begin with a full inner guidance system audit. We move through whatever the day calls for: somatic work, belief repatterning, breathwork, Signal Method, pendulum alignment, business strategy if you are building something.',
    ].join('\n\n'),
    whatsIncludedLabel: "What's included",
    whatsIncludedItems: [
      'A full day, 10am to 5pm UK, with breaks',
      'In person at the Hampton studio, or virtual via Zoom',
      'Pre-day intake form and a 30-minute scoping call the week before',
      'The day itself: nervous-system work, somatic enquiry, decision mapping, integration',
      'Lunch and refreshments included if in person',
      'A 60-minute integration call two weeks later',
    ].join('\n'),
    pricingLabel: 'Investment',
    pricingBody: 'By enquiry. Each One Day is shaped around the person it is for.',
    ctaLabel: 'Send an enquiry below',
    ctaUrl: '#enquire',
    pricePence: 0,
    currency: 'gbp',
    isRecurring: false,
    mailchimpTag: 'One Day Intensive',
    grantsResetRoomAccess: false,
    displayOrder: 30,
  });

  // ═══ Section landing pages + standalone ═══
  await ensure(strapi, 'api::generic-page.generic-page', 'the-work', {
    title: 'Your inner world already knows.',
    kicker: 'Work with Anna',
    kickerColour: '#F280AA',
    intro: 'Most people arrive here after trying everything else. The therapy. The journalling. The courses. The spiritual work. Getting all the way to the insight, and then hitting the same wall. This work meets you in the body, where the patterns actually live.',
  });

  await ensure(strapi, 'api::generic-page.generic-page', 'experiences-landing', {
    title: 'Workshops, retreats, and reset days.',
    kicker: 'Experiences',
    kickerColour: '#7BAFDD',
    intro: 'Group sessions held on the houseboat at Taggs Island, online, and in corporate spaces. A few times a year, a small group comes to the island for a full reset day. Water outside, no agenda, just space to come back to yourself.',
  });

  await ensure(strapi, 'api::generic-page.generic-page', 'mantras', {
    title: 'Mantras',
    kicker: 'Life · Rituals and Energy',
    kickerColour: '#FAA21B',
    tagline: 'Short practices to bring you back to yourself. 60 to 90 seconds each.',
    intro: 'These are not affirmations. They are somatic anchors — phrases paired with breath and body awareness to help regulate your nervous system in real time. Each one comes from the "Come Back to Yourself" series.',
  });

  await ensure(strapi, 'api::generic-page.generic-page', 'cosmic-forecast', {
    title: 'Cosmic Forecast',
    kicker: 'Life · Rituals and Energy',
    kickerColour: '#FAA21B',
    tagline: "This week's energy, moon phase, and stone.",
  });

  await ensure(strapi, 'api::generic-page.generic-page', 'contact', {
    title: 'Contact',
    kicker: 'Say Hello',
    kickerColour: '#6E3A5A',
  });

  await ensure(strapi, 'api::generic-page.generic-page', 'welcome', {
    title: "You're in.",
    kicker: 'Reset Letters · Confirmation',
    kickerColour: '#F280AA',
    intro: [
      'Welcome to Reset Letters. You are now a Founding Member, which means you get full access to everything, for life. No charge. Ever.',
      'Your first edition will land in your inbox on **22 June 2026**. Until then, here are three things you can do:',
    ].join('\n\n'),
  });

  await ensure(strapi, 'api::generic-page.generic-page', 'terms', {
    title: 'Terms & Conditions',
    kicker: 'Legal',
    kickerColour: '#8C8880',
  });

  await ensure(strapi, 'api::generic-page.generic-page', 'privacy', {
    title: 'Privacy Policy',
    kicker: 'Legal',
    kickerColour: '#8C8880',
  });

  await seedTestimonials(strapi);
  await seedPressMentions(strapi);
  await seedCertifications(strapi);
  await seedShopCategories(strapi);
  await seedStandalonePages(strapi);

  strapi.log.info('[seed-pages] Page content seed run complete');
}

/**
 * Seed core standalone pages (Privacy, Terms, Mission placeholder) in the
 * generic-page collection so Anna can edit them in CMS instead of asking
 * dev to update hardcoded JSX. Idempotent — gated on slug.
 *
 * Each entry sets the kicker/title and a starter body. The frontend
 * resolves these via the /[slug] catch-all route at web/app/[slug]/page.tsx.
 */
async function seedStandalonePages(strapi) {
  const samples = [
    {
      slug: 'privacy',
      title: 'Privacy Policy',
      kicker: 'Legal',
      kickerColour: '#6E3A5A',
      tagline: 'How we collect, use, and protect your personal information.',
      intro: [
        'Last updated: May 2026',
        '',
        '1. Who We Are',
        'Anna Lou Wellness is a sole trader based in London, United Kingdom, operated by Anna Lou Scaife. When we refer to "we", "us", or "our" in this policy, we mean Anna Lou Wellness. Our website is annalouwellness.com. For data protection enquiries, contact: hello@annalouwellness.com.',
        '',
        '2. Information We Collect',
        'We may collect the following personal data: Identity data (name, email address, phone number), Contact data (postal address for product orders), Transaction data (purchase history, payment method — card details are processed by Stripe and never stored on our servers), Coaching data (notes from coaching sessions, stored securely and confidentially), Subscription data (email address when you subscribe to our Substack newsletter), Technical data (IP address, browser type, device information, pages visited via analytics), and Quiz/form data (responses to wellness quizzes or enquiry forms).',
        '',
        '3. How We Use Your Information',
        'We use your data to process orders, payments, and shipping; deliver coaching sessions and programme materials; manage your Reset Room membership; respond to enquiries and provide customer support; send order confirmations and shipping updates; deliver newsletter content (via Substack, only if you subscribe); and improve our website and services through anonymous analytics. We do not sell, rent, or share your personal data with third parties for marketing purposes.',
        '',
        '4. Legal Basis for Processing (GDPR)',
        'We process your data under the following legal bases: Contract (to fulfil orders, deliver services, and manage memberships), Consent (for newsletter subscriptions and non-essential cookies), Legitimate interest (to improve our services and website experience), and Legal obligation (to comply with tax and accounting requirements).',
        '',
        '5. Third-Party Services',
        'We use Stripe for secure payment processing (PCI DSS compliant), Substack for newsletter delivery, YouTube for embedded video content, Cloudinary for image hosting, Vercel/Coolify for website hosting, and Instagram/Facebook/YouTube for social media links (no tracking until you click). Each service operates under its own privacy policy.',
        '',
        '6. Cookies',
        'Our website uses essential cookies (session management, cart storage, cookie consent preference) required for the site to function, and optional analytics cookies (anonymous usage data, consent-based). You can decline non-essential cookies via the banner shown on your first visit or manage cookies through your browser settings.',
        '',
        '7. Your Rights (GDPR)',
        'Under the UK GDPR, you have the right to: Access (request a copy of your data), Rectification (correct inaccurate data), Erasure (request deletion — "right to be forgotten"), Restriction (limit how we use your data), Portability (machine-readable format), Objection (object to legitimate-interests processing), and Withdraw consent (unsubscribe or withdraw cookie consent any time). To exercise these rights email hello@annalouwellness.com. We respond within 30 days.',
        '',
        '8. Data Retention',
        'Order data is retained for 6 years (UK tax law). Coaching session notes are retained for 12 months after the last session, then securely deleted. Enquiry form data is retained for 12 months. Newsletter subscribers stay until they unsubscribe. Analytics data is anonymised and retained for 26 months. You may request deletion at any time, subject to our legal obligations.',
        '',
        '9. Data Security',
        'We use SSL/HTTPS encryption across our entire website. Payment data is handled by Stripe (PCI DSS Level 1 certified) and is never stored on our servers. Access to personal data is restricted to authorised individuals only. In the unlikely event of a data breach, we will notify affected individuals and the ICO within 72 hours as required by GDPR.',
        '',
        '10. Children’s Privacy',
        'Our services are not directed at children under 16. We do not knowingly collect personal data from children. If you believe a child has provided us with personal data, please contact us and we will delete it promptly.',
        '',
        '11. Changes to This Policy',
        'We may update this policy from time to time. Changes will be posted on this page with an updated date. We encourage you to review this policy periodically.',
        '',
        '12. Contact & Complaints',
        'For questions about this privacy policy or to exercise your data rights: hello@annalouwellness.com. If you are unsatisfied with how we handle your data, you have the right to lodge a complaint with the Information Commissioner’s Office (ICO): ico.org.uk.',
        '',
        'This is a template privacy policy. Please have it reviewed by a legal professional before publishing.',
      ].join('\n'),
      seoDescription: 'How Anna Lou Wellness collects, uses, stores, and protects your personal information. GDPR compliant, UK-based.',
    },
    {
      slug: 'terms',
      title: 'Terms & Conditions',
      kicker: 'Legal',
      kickerColour: '#6E3A5A',
      tagline: 'The terms that govern purchases, bookings, and use of our services.',
      intro: [
        'Last updated: May 2026',
        '',
        '1. General',
        'These terms and conditions ("Terms") govern all purchases, bookings, and use of services provided through annalouwellness.com, operated by Anna Lou Wellness, a sole trader based in London, United Kingdom. By placing an order, booking a session, or subscribing to a membership, you agree to these Terms in full. If you do not agree, please do not use this website.',
        '',
        '2. Services',
        'Anna Lou Wellness provides one-to-one coaching and therapy sessions (in-person and online), group workshops, retreats, and day experiences, corporate wellbeing programmes and speaking engagements, the Reset Room monthly digital membership, online courses and digital downloads, and handmade jewellery and physical products. Wellness coaching is not a substitute for medical or psychological treatment. If you are experiencing a mental health crisis, please contact your GP or the Samaritans (116 123). Anna Lou Wellness does not diagnose, treat, or claim to cure any medical condition.',
        '',
        '3. Orders & Payment',
        'All prices are in GBP (£) and include VAT where applicable. Payment is accepted by credit/debit card via Stripe. Orders are confirmed by email once payment is received. We reserve the right to cancel orders if products are out of stock, in which case a full refund will be issued within 5 working days.',
        '',
        '4. Coaching & Sessions',
        'Bookings for one-to-one coaching sessions are confirmed upon full payment. Cancellation: 48+ hours notice — full reschedule or refund. 24-48 hours notice — one reschedule offered, no refund. Less than 24 hours or no-show — no refund or reschedule. Sessions are confidential. Any information shared remains private unless there is a safeguarding concern, in which case we may be legally required to share information with the appropriate authorities.',
        '',
        '5. Retreats, Workshops & Events',
        'Places on retreats and workshops are secured by a non-refundable deposit unless otherwise stated. Cancellation: 30+ days before — full refund minus deposit. 14-30 days before — 50% refund. Less than 14 days — no refund (transfer to another person permitted). We reserve the right to cancel or reschedule events due to low attendance or unforeseen circumstances. In such cases, a full refund including deposit will be issued.',
        '',
        '6. The Reset Room Membership',
        'The Reset Room is a recurring monthly subscription. You may cancel at any time; access continues until the end of the current billing period. No partial refunds are given for the current month. Membership content is for personal use only and may not be shared, reproduced, or distributed.',
        '',
        '7. Digital Downloads',
        'Digital products (guides, workbooks, audios) are delivered electronically. Due to their nature, digital downloads are non-refundable once accessed or downloaded. You receive a personal, non-transferable licence to use the content for your own purposes.',
        '',
        '8. Physical Products & Shipping',
        'We ship to the United Kingdom and internationally. Orders are typically dispatched within 2-3 working days. UK delivery: 3-5 working days (Royal Mail). International delivery: 7-14 working days. Shipping costs are calculated at checkout. We are not responsible for delays caused by postal services or customs. Risk passes to you upon delivery.',
        '',
        '9. Returns & Refunds',
        'If you are not satisfied with a physical product, you may return unused items in their original packaging within 14 days of delivery for a full refund. To initiate a return, email hello@annalouwellness.com with your order number. As many of our products are handmade or contain natural crystals, slight variations in colour, size, and appearance are normal and not considered defects. Personalised items are non-returnable unless faulty.',
        '',
        '10. Corporate Bookings',
        'Corporate wellbeing sessions, speaking engagements, and bespoke programmes are quoted individually. A signed agreement and 50% deposit are required to confirm the booking. The balance is due 7 days before the event. Cancellation by the client within 14 days of the event forfeits the deposit.',
        '',
        '11. Intellectual Property',
        'All content on this website (text, photographs, illustrations, video, audio, branding, and design) is the intellectual property of Anna Lou Wellness and protected by UK copyright law. Reproduction, distribution, or commercial use without written permission is prohibited.',
        '',
        '12. Limitation of Liability',
        'Anna Lou Wellness provides coaching, education, and wellness support. Participation in any programme, session, or event is at your own risk. We accept no liability for any loss, injury, or damage arising from your use of our services, products, or content, to the fullest extent permitted by law.',
        '',
        '13. Governing Law',
        'These Terms are governed by the laws of England and Wales. Any disputes shall be subject to the exclusive jurisdiction of the English courts.',
        '',
        '14. Contact',
        'For questions about these Terms, please contact: hello@annalouwellness.com',
        '',
        'This is a template document. Please have it reviewed by a legal professional before publishing.',
      ].join('\n'),
      seoDescription: 'Terms and conditions for Anna Lou Wellness services, products, coaching, retreats, digital downloads, and the Reset Room membership.',
    },
    {
      slug: 'mission',
      title: 'Our Mission',
      kicker: 'About',
      kickerColour: '#6E3A5A',
      tagline: 'What we believe, why this work matters.',
      intro: 'Edit this page in Strapi under "Pages · Standalone" to write the mission statement. This placeholder exists so the URL /mission resolves and you can link to it from the footer.',
    },
    // Note: the remaining hardcoded SubPage pages (/about/press,
    // /about/partnerships, /community/resources,
    // /the-work/ways-to-work-with-me) historically used the
    // generic-page collection but with hyphen-prefixed legacy slugs.
    // We seed entries with both legacy AND clean slugs so editors can
    // discover them either way.
    {
      slug: 'about-press',
      title: 'Press & Features',
      kicker: 'About',
      kickerColour: '#6E3A5A',
      tagline: 'Anna in the press.',
      intro: 'For press enquiries, interview requests, or partnership coverage, email hello@annalouwellness.com.\n\nAnna has been featured across British print and broadcast for over twenty years — across the early Anna Lou of London years at Harrods, Selfridges, Harvey Nichols, and Liberty, and more recently the coaching, the houseboat, and the pivot.\n\nFull press kit and high-resolution photography available on request.',
      ctaLabel: 'Press enquiries',
      ctaUrl: '/contact',
    },
    {
      slug: 'about-partnerships',
      title: 'Work With Me',
      kicker: 'About',
      kickerColour: '#6E3A5A',
      tagline: 'Brand collaborations, speaking, corporate wellbeing.',
      intro: 'I work with a small number of brands each year on partnerships that align with the values of Anna Lou Wellness — somatic, honest, body-led, allergic to gloss.\n\nI also speak at events, run corporate wellbeing days, and host houseboat retreats for teams. For all enquiries, please use the form on the contact page or email hello@annalouwellness.com.\n\nI reply to every enquiry personally within 48 hours.',
      ctaLabel: 'Send an enquiry',
      ctaUrl: '/contact',
    },
    {
      slug: 'community-resources',
      title: 'Resource Library',
      kicker: 'Community',
      kickerColour: '#7BAFDD',
      tagline: 'Free guides, downloads, and reading lists.',
      intro: 'The Nervous System Decoder is the free starter guide — seven self-audit questions and three small practices. Download it from the Decoder page.\n\nFor deeper resources, the Reset Room membership opens the full vault of guided journeys, monthly live calls, and the Signal Method workbook.\n\nReading list, podcast recommendations, and additional free downloads will appear here as Anna releases them.',
      ctaLabel: 'Get the free Decoder',
      ctaUrl: '/free/nervous-system-decoder',
    },
    {
      slug: 'the-work-ways-to-work-with-me',
      title: 'Ways to Work with Me',
      kicker: 'Work with Anna',
      kickerColour: '#F280AA',
      tagline: 'A clear map of every door in.',
      intro: 'There are several ways to begin, each designed for a different stage of the work.\n\nStart free with the Nervous System Decoder — a guide and seven-question self-audit that opens the door.\n\nFor ongoing support without 1:1 commitment, the Reset Room is £25/month — monthly live call, vault of guided journeys, private podcast.\n\nFor a specific moment or decision, a single Reset Session is the most direct entry. Ninety minutes, one knot, one clear shift.\n\nFor deeper work, The Reset is the six-week 1:1 programme. Signal is the twelve-week deeper container. Signal & Build is twelve weeks for founders rebuilding their business from the body up.\n\nFor one concentrated day, One Day on the houseboat is bookable by enquiry.\n\nNot sure which fits? Take the two-minute Ask Anna assessment for a personal recommendation.',
      ctaLabel: 'Take the 2-minute assessment',
      ctaUrl: '/ask-anna',
    },
    {
      slug: 'the-returning-circle',
      title: 'The Returning Circle',
      kicker: 'Community',
      kickerColour: '#231F20',
      tagline: 'Tuesday evenings at The Hare and the Moon, Twickenham.',
      intro: 'Every Tuesday I hold a circle at The Hare and the Moon in Twickenham. Donation-based. No agenda except being in the room together.\n\nConnection is not a concept. It is biological. The nervous system regulates in proximity to other regulated nervous systems. The Returning Circle is built around that.\n\nThe Circle runs every week without exception. No waitlist needed. Come on Tuesday. Doors from 6.30pm, circle starts at 7pm sharp.\n\nAddress: The Hare and the Moon, Twickenham. £donation, no minimum.',
      ctaLabel: 'Find the address',
      ctaUrl: '/contact',
    },
  ];

  for (const sample of samples) {
    try {
      const existing = await strapi.documents('api::generic-page.generic-page').findMany({
        filters: { slug: sample.slug },
        limit: 1,
      });
      if (existing && existing.length > 0) continue;
      await strapi.documents('api::generic-page.generic-page').create({
        data: sample,
        status: 'published',
      });
      strapi.log.info(`[seed-pages] Created standalone page: /${sample.slug}`);
    } catch (err) {
      strapi.log.warn(`[seed-pages] standalone page seed skipped (${sample.slug}): ${err.message}`);
    }
  }
}

/**
 * Seed the shop category hierarchy Anna asked for:
 *   - Jewellery (parent)
 *     - Bracelets
 *     - Earrings
 *     - Necklaces
 *     - Charms
 *   - Crystals
 *   - Sage & Palo Santo
 *   - Gifts
 *
 * Idempotent: gates on slug. Creates parents first so children can
 * reference them. Anna can rename / add / hide categories in the
 * admin without losing data.
 */
async function seedShopCategories(strapi) {
  const findBySlug = async (slug) => {
    const found = await strapi.documents('api::product-category.product-category').findMany({
      filters: { slug },
      limit: 1,
    });
    return found && found.length > 0 ? found[0] : null;
  };
  const ensureCategory = async ({ slug, name, sort_order, parentSlug = null, description = null }) => {
    const existing = await findBySlug(slug);
    if (existing) return existing;
    const data = { slug, name, sort_order, is_visible_in_nav: true };
    if (description) data.description = description;
    if (parentSlug) {
      const parent = await findBySlug(parentSlug);
      if (parent) data.parent = parent.id;
    }
    try {
      const created = await strapi.documents('api::product-category.product-category').create({
        data,
        status: 'published',
      });
      strapi.log.info(`[seed-pages] Created product-category: ${name}${parentSlug ? ` (under ${parentSlug})` : ''}`);
      return created;
    } catch (err) {
      strapi.log.warn(`[seed-pages] product-category seed skipped (${slug}): ${err.message}`);
      return null;
    }
  };

  // Parents first (sort_order spaced so Anna can slot new ones between).
  await ensureCategory({ slug: 'jewellery', name: 'Jewellery', sort_order: 10 });
  await ensureCategory({ slug: 'crystals', name: 'Crystals', sort_order: 20 });
  await ensureCategory({ slug: 'sage-and-palo-santo', name: 'Sage & Palo Santo', sort_order: 30 });
  await ensureCategory({ slug: 'gifts', name: 'Gifts', sort_order: 40 });

  // Jewellery sub-categories.
  await ensureCategory({ slug: 'bracelets', name: 'Bracelets', sort_order: 1, parentSlug: 'jewellery' });
  await ensureCategory({ slug: 'earrings', name: 'Earrings', sort_order: 2, parentSlug: 'jewellery' });
  await ensureCategory({ slug: 'necklaces', name: 'Necklaces', sort_order: 3, parentSlug: 'jewellery' });
  await ensureCategory({ slug: 'charms', name: 'Charms', sort_order: 4, parentSlug: 'jewellery' });
}

/**
 * Press mentions for the homepage 'As seen in' strip. Idempotent — gated
 * on name + the homepage flag so re-runs don't duplicate. Anna can replace
 * the styled text with real logo uploads via the Strapi admin; the name
 * + sort_order persist.
 */
async function seedPressMentions(strapi) {
  const samples = [
    { name: 'Harrods', sort_order: 1 },
    { name: 'Selfridges', sort_order: 2 },
    { name: 'Harvey Nichols', sort_order: 3 },
    { name: 'QVC Japan', sort_order: 4 },
    { name: 'The Telegraph', sort_order: 5 },
    { name: 'Stylist', sort_order: 6 },
    { name: 'SheerLuxe', sort_order: 7 },
  ];
  for (const s of samples) {
    try {
      const existing = await strapi.documents('api::press-mention.press-mention').findMany({
        filters: { name: s.name },
        limit: 1,
      });
      if (existing && existing.length > 0) continue;
      await strapi.documents('api::press-mention.press-mention').create({
        data: { ...s, is_homepage_featured: true, is_active: true },
        status: 'published',
      });
      strapi.log.info(`[seed-pages] Created press-mention: ${s.name}`);
    } catch (err) {
      strapi.log.warn(`[seed-pages] press-mention seed skipped (${s.name}): ${err.message}`);
    }
  }
}

/**
 * Certification badges for the homepage 'Certified' strip. Same pattern.
 */
async function seedCertifications(strapi) {
  const samples = [
    { name: 'ICF', label: 'Accredited', colour: '#1a5276', sort_order: 1 },
    { name: 'CPD', label: 'Certified', colour: '#c0392b', sort_order: 2 },
    { name: 'TRE®', label: 'Provider', colour: '#27ae60', sort_order: 3 },
  ];
  for (const s of samples) {
    try {
      const existing = await strapi.documents('api::certification.certification').findMany({
        filters: { name: s.name, label: s.label },
        limit: 1,
      });
      if (existing && existing.length > 0) continue;
      await strapi.documents('api::certification.certification').create({
        data: { ...s, is_homepage_featured: true, is_active: true },
        status: 'published',
      });
      strapi.log.info(`[seed-pages] Created certification: ${s.name} ${s.label}`);
    } catch (err) {
      strapi.log.warn(`[seed-pages] certification seed skipped (${s.name}): ${err.message}`);
    }
  }
}

/**
 * Testimonials don't have a slug — gate on reviewer_name + tags so re-runs
 * don't create duplicates and Anna's edits stay safe.
 */
async function seedTestimonials(strapi) {
  const samples = [
    {
      reviewer_name: 'Charlotte H.',
      reviewer_location: 'London — Reset alumna',
      quote: 'I came in wound tight and left lighter than I had felt in years. Anna sees what is underneath the surface story and works there. The change has held.',
      rating: 5,
      tags: 'the-reset',
      sort_order: 1,
      is_featured: true,
    },
    {
      reviewer_name: 'Priya M.',
      reviewer_location: 'Founder, F&B startup',
      quote: 'Signal & Build did what no business coach has ever done — it sorted the inner stuff and the company strategy at the same time. The decisions I have made since feel solid in my body.',
      rating: 5,
      tags: 'signal-and-build',
      sort_order: 1,
      is_featured: true,
    },
    {
      reviewer_name: 'Emma R.',
      reviewer_location: 'Houseboat retreat, March 2026',
      quote: 'Six hours on the river with five other women. No phones. Real conversation, real breath work, real food. I left with a clarity I had been chasing for two years.',
      rating: 5,
      tags: 'retreats',
      sort_order: 1,
      is_featured: true,
    },
    {
      reviewer_name: 'Sofia T.',
      reviewer_location: 'Signal cohort, autumn 2025',
      quote: 'Twelve weeks is exactly the right amount of time. By week six things were shifting. By week twelve I was a different person — recognisable to myself, finally.',
      rating: 5,
      tags: 'signal',
      sort_order: 1,
    },
    {
      reviewer_name: 'Rachel B.',
      reviewer_location: 'One Day on the houseboat',
      quote: 'A full day with Anna unpicked things I have been carrying since my twenties. I have done years of therapy. This was different — the body knew first.',
      rating: 5,
      tags: 'one-day',
      sort_order: 1,
    },
    {
      reviewer_name: 'James K.',
      reviewer_location: 'Head of People, B-Corp tech',
      quote: 'Anna ran a half-day for our leadership team on the houseboat. Six months later people are still referencing the framework she taught. Genuine cultural impact.',
      rating: 5,
      tags: 'corporate',
      sort_order: 1,
    },
  ];

  for (const sample of samples) {
    try {
      const existing = await strapi.documents('api::testimonial.testimonial').findMany({
        filters: {
          reviewer_name: sample.reviewer_name,
          tags: sample.tags,
        },
        limit: 1,
      });
      if (existing && existing.length > 0) continue;
      await strapi.documents('api::testimonial.testimonial').create({
        data: { ...sample, is_active: true },
        status: 'published',
      });
      strapi.log.info(`[seed-pages] Created testimonial: ${sample.reviewer_name} (${sample.tags})`);
    } catch (err) {
      strapi.log.warn(`[seed-pages] Testimonial seed skipped: ${err.message}`);
    }
  }
}

module.exports = seedPages;
