"""Extract homepage CMS field fallbacks from page.tsx and emit as a seed snippet."""
import re
import sys
import os
import io

# Force UTF-8 stdout so → and similar characters survive on Windows.
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

# Resolve from this file's location → ../web/app/page.tsx (cross-platform)
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, os.pardir))
SRC = sys.argv[1] if len(sys.argv) > 1 else os.path.join(REPO_ROOT, 'web', 'app', 'page.tsx')
UID = sys.argv[2] if len(sys.argv) > 2 else 'api::homepage.homepage'
OUT = sys.argv[3] if len(sys.argv) > 3 else None

with open(SRC, 'r', encoding='utf-8') as fh:
    content = fh.read()

# Match every f(cms, 'fieldName', 'fallback value')
# The fallback is delimited by either ' or " and may contain escaped chars
pattern = re.compile(
    r"""f\(\s*cms,\s*['"](?P<key>[a-zA-Z0-9_]+)['"]\s*,\s*(?P<q>['"])(?P<val>(?:\\.|(?!(?P=q)).)*)(?P=q)\s*\)""",
    re.DOTALL,
)

seen = {}
for m in pattern.finditer(content):
    k = m.group('key')
    v = m.group('val')
    # Un-escape standard sequences
    v = v.replace("\\'", "'").replace('\\"', '"').replace('\\n', '\n').replace('\\t', '\t')
    if k not in seen:
        seen[k] = v

out = []
short_src = os.path.relpath(SRC, REPO_ROOT).replace(os.sep, '/')
out.append(f"  // {len(seen)} fields extracted from {short_src} (auto-generated by Docs/_extract_homepage_seed.py)")
out.append(f"  await ensureSingleType(strapi, '{UID}', {{")
for k, v in seen.items():
    esc = v.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n').replace('\r', '')
    out.append(f'    {k}: "{esc}",')
out.append("  });")
result = '\n'.join(out) + '\n'
if OUT:
    with open(OUT, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(result)
    print(f"Wrote {len(seen)} fields → {OUT}")
else:
    print(result)
